version: "3.8"

services:
  db:
    image: postgres:18.0-alpine3.22
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./volume/postgres:/persistent_data/postgres
      - ./init_product.sql:/docker-entrypoint-initdb.d/init_product.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    
  pgAdmin4:
    image: dpage/pgadmin4:9.8
    ports:
      - "5050:80"
    depends_on:
      - db