apiVersion: v1
kind: Namespace
metadata:
  name: agent-ecosystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2a-app
  namespace: agent-ecosystem
spec:
  replicas: 2
  selector:
    matchLabels:
      app: a2a-app
  template:
    metadata:
      labels:
        app: a2a-app
    spec:
      containers:
        - name: a2a-app
          image: your-registry/a2a-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: PAYMENT_AGENT_SERVER_HOST
              value: "0.0.0.0"
            - name: PAYMENT_AGENT_SERVER_PORT
              value: "8081"
            - name: MCP_SERVER_HOST_PAYMENT
              value: payment-tool
            - name: MCP_SERVER_PORT_PAYMENT
              value: "8000"
            - name: MCP_SERVER_HOST_SALESPERSON
              value: salesperson-tool
            - name: MCP_SERVER_PORT_SALESPERSON
              value: "8001"
            - name: MCP_PAYMENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: agent-secrets
                  key: mcp-payment-token
            - name: MCP_SALESPERSON_TOKEN
              valueFrom:
                secretKeyRef:
                  name: agent-secrets
                  key: mcp-salesperson-token
          readinessProbe:
            httpGet:
              path: /.well-known/agent-card.json
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /.well-known/agent-card.json
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: a2a-app
  namespace: agent-ecosystem
spec:
  type: ClusterIP
  selector:
    app: a2a-app
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-tool
  namespace: agent-ecosystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-tool
  template:
    metadata:
      labels:
        app: payment-tool
    spec:
      containers:
        - name: payment-tool
          image: your-registry/payment-tool:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MCP_SERVER_HOST_PAYMENT
              value: "0.0.0.0"
            - name: MCP_SERVER_PORT_PAYMENT
              value: "8000"
            - name: MCP_PAYMENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: agent-secrets
                  key: mcp-payment-token
          readinessProbe:
            httpGet:
              path: /mcp
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /mcp
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: payment-tool
  namespace: agent-ecosystem
spec:
  type: ClusterIP
  selector:
    app: payment-tool
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesperson-tool
  namespace: agent-ecosystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salesperson-tool
  template:
    metadata:
      labels:
        app: salesperson-tool
    spec:
      containers:
        - name: salesperson-tool
          image: your-registry/salesperson-tool:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: MCP_SERVER_HOST_SALESPERSON
              value: "0.0.0.0"
            - name: MCP_SERVER_PORT_SALESPERSON
              value: "8001"
            - name: MCP_SALESPERSON_TOKEN
              valueFrom:
                secretKeyRef:
                  name: agent-secrets
                  key: mcp-salesperson-token
          readinessProbe:
            httpGet:
              path: /mcp
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /mcp
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: salesperson-tool
  namespace: agent-ecosystem
spec:
  type: ClusterIP
  selector:
    app: salesperson-tool
  ports:
    - name: http
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adk-web
  namespace: agent-ecosystem
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adk-web
  template:
    metadata:
      labels:
        app: adk-web
    spec:
      containers:
        - name: adk-web
          image: your-registry/adk-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ADK_WEB_HOST
              value: "0.0.0.0"
            - name: ADK_WEB_PORT
              value: "8080"
            - name: PAYMENT_AGENT_SERVER_HOST
              value: a2a-app
            - name: PAYMENT_AGENT_SERVER_PORT
              value: "8081"
            - name: MCP_SERVER_HOST_PAYMENT
              value: payment-tool
            - name: MCP_SERVER_PORT_PAYMENT
              value: "8000"
            - name: MCP_SERVER_HOST_SALESPERSON
              value: salesperson-tool
            - name: MCP_SERVER_PORT_SALESPERSON
              value: "8001"
            - name: MCP_PAYMENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: agent-secrets
                  key: mcp-payment-token
            - name: MCP_SALESPERSON_TOKEN
              valueFrom:
                secretKeyRef:
                  name: agent-secrets
                  key: mcp-salesperson-token
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: adk-web
  namespace: agent-ecosystem
spec:
  type: ClusterIP
  selector:
    app: adk-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: agent-secrets
  namespace: agent-ecosystem
stringData:
  mcp-payment-token: "replace-with-real-payment-token"
  mcp-salesperson-token: "replace-with-real-salesperson-token"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adk-web
  namespace: agent-ecosystem
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: adk.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adk-web
                port:
                  number: 80
