import enum


class Status(enum.Enum):
    SUCCESS = "00"
    FAILURE = "01"
    PRODUCT_NOT_FOUND = "02"
    QUANTITY_EXCEEDED = "03"
    JSON_INVALID = "04"
    JSON_RPC_VERSION_INVALID = "05"
    METHOD_NOT_FOUND = "06"
    MISSING_PARAMS = "07"
    INVALID_PARAMS = "08"
    MISSING_TASK_METADATA = "09"
    INVALID_TASK_PAYLOAD = "10"
    UNKNOWN_ERROR = "99"
