import enum


class Status(enum.Enum):
    SUCCESS = "00"
    FAILURE = "01"
    PRODUCT_NOT_FOUND = "02"
    QUANTITY_EXCEEDED = "03"
    TOOL_NOT_FOUND = "04"
    INVALID_TOOL_ARGUMENT = "05"
    TOOL_EXECUTION_ERROR = "06"
    INVALID_REQUEST = "07"
    INVALID_JSON = "08"
    UNKNOWN_ENDPOINT = "09"
    UPSTREAM_SERVICE_ERROR = "10"
    UNKNOWN_ERROR = "99"
